time = input ("How Many Seconds Are Left Till Launch\n[")
oxygen = input ("How Many Oxygen Packs Are Left\n[")
food = input("How Many Food Packs Are Left\n[")
water = input("How Many Water Packs Are Left\n[")
print("Countdown: "+time)
print("Oxygen_Tanks: "+oxygen)
print("Food_Packs: "+food)
print("Water_Packs: "+water)
oxygen = input("Confirm Oxygen Packs\n[")
print("Countdown: "+time)
print("Oxygen_Tanks: "+oxygen)
print("Food_Packs: "+food)
print("Water_Packs: "+water)