time = input ("Countdown")
oxygen = input ("Oxygen_Tanks")
food = input("Food_Packs")
water = input("Water_Packs")
print("Countdown"+time)
print("Oxygen_Tanks"+oxygen)
print("Food_Packs"+food)
print("Water_Packs"+water)
oxygen = input("Confirm Oxygen Packs")
print("Countdown"+time)
print("Oxygen_Tanks"+oxygen)
print("Food_Packs"+food)
print("Water_Packs"+water)