answer1 = int(input("Give a number more than 7.\n["))
answer2 = int(input("Give a number less than 91.\n["))
answer3 = int(input("Give a number equal to  15.\n["))
answer4 = int(input("Give a number more than or equal to 73.\n["))
answer5 = int(input("Give a number less than or equal to 932.\n["))
print(answer1>7)
print(answer2<91)
print(answer3==15)
print(answer4>=73)
print(answer5<=932)
